volumes:
  pgdata: 

services:
  database:
    image: postgres:latest
    container_name: database
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=shelldb
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "shelldb"]
      interval: 5s
      retries: 5
      start_period: 10s
      timeout: 5s

  fastapi-app:
    container_name: shell-fastapi
    build: .
    environment:
      - PGUSER=postgres
      - PGPASSWORD=password
      - PGHOST=database
      - PGDATABASE=shelldb
      - PGPORT=5432
    ports:
      - "8000:8000"
    depends_on:
      database:
        condition: service_healthy 
